chagayh/CIY_app

- app/src/main/java/com/example/ciy/HomeFragment.java
added 400 recipes approximately, home fragment now syncs with the global recipes
> added 400 recipe see description 

- app/google-services.json
- app/src/main/java/com/example/ciy/Recipe.java
Desc: getters in objects related to firestore MOST be public even
when android studio says otherwise
Issue: None
> ***Important*** fixed important bug

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/loginActivity.java
- app/src/main/res/menu/tool_bar_buttons.xml
Desc: as stated above
Issue: None
> Add fireStore record to google signin

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
Desc: added backpress mechanics, maybe needs work.
Issues: None
> Back press support(needs work)

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
If the user sign in with google, the url of the photo will be downloaded
and presented on the app, otherwise, default profile image will be
shown.
> Added profile photo option for google users

- .idea/dictionaries/Charlool.xml
- app/build.gradle
- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/res/layout/activity_bottom_navigation_bar.xml
Desc: added padding and constant height to toolbar, little bit of
cosmetics and fixed dialog issue
> Fixed Toolbar hiding layout issue

- app/src/main/java/com/example/ciy/HomeFragment.java
> Without dogs

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/RecipeAdapter.java
- app/src/main/java/com/example/ciy/RecipeFragment.java
- app/src/main/java/com/example/ciy/SharedData.java
Desc: now when pressed like a recipe pointer will be saved to user's
database.
Issue: missing documentation and cleanup to the code, will be done on
wednesday
> Added favorites foundations (not full commit)

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/RecipeAdapter.java
- app/src/main/java/com/example/ciy/RecipeFragment.java
- app/src/main/java/com/example/ciy/SharedData.java
Added favorites foundations (not full commit)
> fix commit

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/LoginActivity.java
- app/src/main/java/com/example/ciy/SplashActivity.java
- app/src/main/java/com/example/ciy/forgotPasswordActivity.java
- app/src/main/res/layout/activity_login.xml
Desc: now SplashActivity is checking if the user already logged in.
if user i logged in we start the app regularly, otherwise we call the
login activity.
> Renamed login to Login and changed user check

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/RecipeAdapter.java
- app/src/main/java/com/example/ciy/RecipeFragment.java
- app/src/main/java/com/example/ciy/SharedData.java
Desc: cleaned the code a bit and shortned the Recycler view enable
logic, we now enable the home fragment directly from the recipe fragment
> Documantation and minor logic changes

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/LoginActivity.java
- app/src/main/java/com/example/ciy/signInActivity.java
Desc: added finish() when going from log in to the home screen and vice
versa, as we do not want to allow the return button default action
> Changed flow and cleaning

- app/src/main/res/layout/recipe_item.xml
Desc: now has ripple effect on cardview
> Added ripple effect

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/SharedData.java
Desc: We now have flow in the main window, when we
press the home button twice it will scroll up to
the top of the recycler view.
other then that when we press the back button from anywhere isn't home
we return to home screen, if we are already in home we exit the app.
> Added flow

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/FavoritesFragment.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/RecipeAdapter.java
- app/src/main/java/com/example/ciy/RecipeFragment.java
- app/src/main/res/layout/activity_searcher.xml
- app/src/main/res/layout/favorite_item.xml
- app/src/main/res/layout/fragment_favorites.xml
Desc: now when pressing like we add the recipe to the favorites screen.
if we unlike we will remove it from the favorite screen.
added support for recepie adapter so he can have 2 different layouts.
few bug fixes
> Added favorites screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/ciy/FavoritesFragment.java
- app/src/main/java/com/example/ciy/ForgotPasswordActivity.java
- app/src/main/java/com/example/ciy/LoginActivity.java
- app/src/main/java/com/example/ciy/SearchRecipeActivity.java
- app/src/main/java/com/example/ciy/SignInActivity.java
- app/src/main/java/com/example/ciy/Window2.java
- app/src/main/res/layout/activity_forgot_password.xml
- app/src/main/res/layout/activity_search_recipe.xml
- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/favorite_item.xml
- app/src/main/res/layout/search_item.xml
Desc: Changed classes without first letter capital, added clickable
event to favorites, and started working on a regular(not firestore
object) recyclerviewer for the searching activities.
> Name changes + Favorites and Search foundation

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/SearchAdapter.java
- app/src/main/java/com/example/ciy/SearchRecipeActivity.java
- app/src/main/res/menu/search_menu.xml
- app/src/main/res/menu/tool_bar_buttons.xml
Desc: When we press the search icon on the top we will have a search
screen where we can filter recipes by name.
TODO: show the recipe screen when pressing on a recipe
> Integrated search inside app

- app/src/main/java/com/example/ciy/IngredientsAdapter.java
- app/src/main/java/com/example/ciy/SearchAdapter.java
- app/src/main/java/com/example/ciy/SearchFragment.java
- app/src/main/java/com/example/ciy/SearchRecipeActivity.java
- app/src/main/res/drawable/ic_pencil.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/ingredient_item.xml
Desc: finished the logic of the ingredients except for clickable delete
draw-able, need to work on the layout and start the filtering activity.
> Updated ingredients search(not UI wise)

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/LoginActivity.java
- app/src/main/res/layout/activity_login.xml
Made the photo of the user to be uploaded fater.
Made the login look more elegant.
> Updated buttom nevigation activity and login layout

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/FavoritesFragment.java
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/java/com/example/ciy/RecipeFragment.java
- app/src/main/java/com/example/ciy/SearchRecipeActivity.java
- app/src/main/java/com/example/ciy/SharedData.java
Desc: Now we can view recipes on the search activity.
Fixed minor bugs
> Added recipe view on search

- app/build.gradle
- app/src/main/java/com/example/ciy/HomeFragment.java
- app/src/main/res/drawable-xxxhdpi/badge_bg_with_shadow.xml
- app/src/main/res/layout/fragment_home.xml
Desc: fixed search issue where creating new fragment every time, now the
fridge should have a badge indicating how many items we have
> Fixed search and start of badge

- app/src/main/java/com/example/ciy/SearchAdapter.java
- app/src/main/java/com/example/ciy/SearchRecipeActivity.java
- app/src/main/java/com/example/ciy/SharedData.java
- app/src/main/res/drawable-xxxhdpi/animation_button.xml
- app/src/main/res/drawable-xxxhdpi/ripple.xml
- app/src/main/res/drawable/toolbar_dropshadow.xml
- app/src/main/res/layout/activity_search_recipe.xml
- app/src/main/res/values/colors.xml
Desc: we now have filter tags (need to add horizental scroll) need to
finish the actual filtering.
> Added infrastructure for filtering

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
> fixed bug - intro shown only the first time entered

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
- app/src/main/java/com/example/ciy/LoginActivity.java
> changed introduce the app every sign in

- app/src/main/java/com/example/ciy/BottomNavigationBar.java
Changes Intro strings and removed titles
> changes intro strings

- app/src/main/java/com/example/ciy/LoginActivity.java
> added comments
